@echo off
echo Создание виртуального окружения...
python -m venv venv
echo Активация окружения...
call venv\Scripts\activate.bat
echo Установка зависимостей...
pip install -r requirements.txt
echo Готово! Окружение создано и активировано.
pause